/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'hub-root':          '#121212',
        'hub-surface':       '#1e1e1e',
        'hub-raised':        '#252526',
        'hub-hover':         '#2a2d2e',
        'hub-active':        '#1a3a3a',
        'hub-input':         '#1e1e1e',
        'hub-code':          '#0d1117',
        'hub-border':        '#333333',
        'hub-border-2':      '#3a3a3a',
        'hub-accent':        '#4fd1c5',
        'hub-accent-hover':  '#38b2a0',
        'hub-warning':       '#d69e2e',
        'hub-danger':        '#e53e3e',
        'hub-success':       '#38a169',
        'hub-link':          '#569cd6',
        'hub-primary':       'rgba(248,250,252,0.94)',
        'hub-secondary':     'rgba(203,213,225,0.82)',
        'hub-tertiary':      'rgba(148,163,184,0.55)',
        'hub-muted':         'rgba(148,163,184,0.30)',
        'agent-code':        '#8b5cf6',
        'agent-review':      '#38a169',
        'agent-devops':      '#ea580c',
        'agent-planner':     '#4fd1c5',
        'agent-test':        '#569cd6',
        'agent-security':    '#d69e2e',
      },
      borderColor: {
        'hub': '#333333',
      },
      borderRadius: {
        'hub-sm':  '4px',
        'hub-md':  '6px',
        'hub-lg':  '8px',
        'hub-xl':  '12px',
        'hub-2xl': '16px',
      },
      transitionDuration: {
        'hub-fast': '120ms',
        'hub':      '180ms',
        'hub-slow': '250ms',
      },
    },
  },
  plugins: [],
};
